apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: travelo
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/travelo_db?createDatabaseIfNotExist=true"
  SPRING_DATASOURCE_USERNAME: "travelo"
