apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: travelo
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: travelo_db
  MYSQL_USER: travelo
  MYSQL_PASSWORD: travelo123

