
---
# pdb-frontend.yml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: travelo-frontend-pdb
  namespace: travelo
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: travelo-frontend

---